[package]
name = "ql-webservice"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
quickql-core = { path = "../quickql-core" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
